apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  namespace: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: codeberg.org/caffeinatedope/blog:latest@sha256:2fdf14f8363244fdecc3109c860ec835a38f8d2cc84a6843594557f2fd6367c4 # {"$imagepolicy": "blog:blog-imagepolicy"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4321
