---
apiVersion: v1
kind: Namespace
metadata:
  name: blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  namespace: blog
spec:
  replicas: 7
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: ghcr.io/caffeinatedope/blog:latest@sha256:f3d712d4cd1e253c5d65a9e94a6518f919e63bf3a37658c1247fec4e39c0f8f1 # {"$imagepolicy": "blog:blog"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4321
