---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-controller
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/cert-manager/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-certs
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-controller
  interval: 10m0s
  path: ./cluster/cert-manager/certs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system