apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/jenkins
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system