apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster/jenkins-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system