apiVersion: apps/v1
kind: Deployment
metadata:
  name: eng-deployment
  namespace: eng
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eng
  template:
    metadata:
      labels:
        app: eng
    spec:
      containers:
      - name: eng
        image: codeberg.org/caffeinatedope/eng-proj:latest@sha256:bf41ed5ffc2205fb7c42dc4274d4d17ab51c73cc12ea6cd70a9600ce6477fb36 # {"$imagepolicy": "eng:eng-imagepolicy"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4322
