apiVersion: apps/v1
kind: Deployment
metadata:
  name: eng-deployment
  namespace: eng
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eng
  template:
    metadata:
      labels:
        app: eng
    spec:
      containers:
      - name: eng
        image: codeberg.org/caffeinatedope/eng-proj:latest@sha256:7c43e5c7e7a9a01327052d904638cc339ac8259a4f8595ec44f38b23f724ddfd # {"$imagepolicy": "eng:eng-imagepolicy"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4322
