apiVersion: apps/v1
kind: Deployment
metadata:
  name: eng-deployment
  namespace: eng
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eng
  template:
    metadata:
      labels:
        app: eng
    spec:
      containers:
      - name: eng
        image: codeberg.org/caffeinatedope/eng-proj:latest@sha256:cb39b48426d1ec1eb372a4006fb53f34a051b4a8b04b6406c506b0df7322b530 # {"$imagepolicy": "eng:eng-imagepolicy"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4322
